/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const SessionId = IDL.Text;
export const UploadResult = IDL.Record({
  'count' : IDL.Nat,
  'allowed' : IDL.Bool,
});
export const Time = IDL.Int;
export const PlanName = IDL.Text;
export const Subscription = IDL.Record({
  'timestamp' : Time,
  'sessionId' : SessionId,
  'planName' : PlanName,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'canUploadImage' : IDL.Func([SessionId], [UploadResult], []),
  'getAllSubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
  'getRatingStats' : IDL.Func(
      [],
      [IDL.Record({ 'averageRating' : IDL.Nat, 'numRatings' : IDL.Nat })],
      ['query'],
    ),
  'recordImageUpload' : IDL.Func([SessionId], [UploadResult], []),
  'recordSubscription' : IDL.Func([SessionId, PlanName], [], []),
  'submitRating' : IDL.Func([SessionId, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const SessionId = IDL.Text;
  const UploadResult = IDL.Record({ 'count' : IDL.Nat, 'allowed' : IDL.Bool });
  const Time = IDL.Int;
  const PlanName = IDL.Text;
  const Subscription = IDL.Record({
    'timestamp' : Time,
    'sessionId' : SessionId,
    'planName' : PlanName,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'canUploadImage' : IDL.Func([SessionId], [UploadResult], []),
    'getAllSubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
    'getRatingStats' : IDL.Func(
        [],
        [IDL.Record({ 'averageRating' : IDL.Nat, 'numRatings' : IDL.Nat })],
        ['query'],
      ),
    'recordImageUpload' : IDL.Func([SessionId], [UploadResult], []),
    'recordSubscription' : IDL.Func([SessionId, PlanName], [], []),
    'submitRating' : IDL.Func([SessionId, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };